services:
  server:
    command: sh -c "npx prisma migrate deploy && npm run dev"
    image: zoai-server
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - ./.env.dev
    volumes: 
      - ./:/usr/src/app
    depends_on:
      - postgres
      - mongo
      - redis
  mongo:
    restart: always
    image: mongo:4.4
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: zoai_db
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db
  redis:
    restart: always
    command: ['redis-server', '--appendonly', 'yes']
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data

  postgres:
    restart: always
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: username
      POSTGRES_DB: zoai-db
    ports:
      - 5434:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data 
